/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna <p/> This program is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License, or (at your option)
 * any later version. <p/> This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details. <p/> You should
 * have received a copy of the GNU Affero General Public License along with this program. If not,
 * see <https://www.gnu.org/licenses/>.
 */

package it.eng.parer.crypto.helper;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Arrays;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.shrinkwrap.api.Archive;
import org.junit.jupiter.api.Test;

import it.eng.parer.entity.HsmSessioneFirma;
import it.eng.parer.entity.IamUser;
import it.eng.parer.firma.crypto.helper.SerieSignatureHelper;
import it.eng.parer.firma.crypto.helper.SigningHelper;
import it.eng.parer.web.helper.ConfigurationHelper;
import it.eng.parer.web.helper.HelperTest;

public class SerieSignatureHelperTest extends HelperTest<SerieSignatureHelper> {
    @Deployment
    public static Archive<?> createTestArchive() {
	return HelperTest.createEnterpriseArchive(SerieSignatureHelperTest.class.getSimpleName(),
		HelperTest.createPaginatorJavaArchive(), HelperTest.createSacerLogJar(),
		HelperTest.createSacerJavaArchive(Arrays.asList(""), SerieSignatureHelperTest.class,
			SerieSignatureHelper.class, SigningHelper.class,
			ConfigurationHelper.class));
    }

    @Test
    void createSessioneFirma_queryIsOk() {
	try {
	    helper.createSessioneFirma(5000l); // admin_generale
	    assertTrue(true);
	} catch (Exception e) {
	    assertNoAutogeneratedSequence(e);
	}
    }

    @Test
    void getActiveSessionsByUser_IamUser_queryIsOk() {
	IamUser user = aIamUser();
	user.setIdUserIam(aLong());
	helper.getActiveSessionsByUser(user);
	assertTrue(true);
    }

    @Test
    void getActiveSessionsByUser_long_queryIsOk() {
	long userId = aLong();
	helper.getActiveSessionsByUser(userId);
	assertTrue(true);
    }

    @Test
    void getBlockedSessionsByUser_IamUser_queryIsOk() {
	IamUser user = aIamUser();
	helper.getBlockedSessionsByUser(user);
	assertTrue(true);
    }

    @Test
    void getBlockedSessionsByUser_long_queryIsOk() {
	long userId = aLong();
	helper.getBlockedSessionsByUser(userId);
	assertTrue(true);
    }

    @Test
    void isAllFileSigned_HsmSessioneFirma_queryIsOk() {
	HsmSessioneFirma session = aHsmSessioneFirma();
	helper.isAllFileSigned(session);
	assertTrue(true);
    }

    private HsmSessioneFirma aHsmSessioneFirma() {
	HsmSessioneFirma session = new HsmSessioneFirma();
	session.setIdSessioneFirma(aLong());
	return session;
    }

    @Test
    void isAllFileSigned_long_queryIsOk() {
	long sessionId = aLong();
	helper.isAllFileSigned(sessionId);
	assertTrue(true);
    }

    @Test
    void findSerieSessione_HsmSessioneFirma_long_queryIsOk() {
	HsmSessioneFirma session = aHsmSessioneFirma();
	long idElenco = aLong();
	helper.findSerieSessione(session, idElenco);
	assertTrue(true);
    }

    @Test
    void findSerieSessione_long_long_queryIsOk() {
	long sessionId = aLong();
	long idElenco = aLong();
	helper.findSerieSessione(sessionId, idElenco);
	assertTrue(true);
    }
}
