/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna <p/> This program is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the License, or (at your option)
 * any later version. <p/> This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details. <p/> You should
 * have received a copy of the GNU Affero General Public License along with this program. If not,
 * see <https://www.gnu.org/licenses/>.
 */

package it.eng.parer.soapWS.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0 2023-12-12T12:58:59.044+01:00 Generated source
 * version: 2.7.0
 *
 */
@WebService(targetNamespace = "http://ws.sacerasi.eng.it/", name = "RecStatoOggettoPing")
@XmlSeeAlso({
        ObjectFactory.class })
public interface RecStatoOggettoPing {

    /**
     *
     * @param cdKeyObject chiave dell'oggetto
     * @param nmAmbiente  nome ambiente
     * @param nmVersatore nome versatore
     *
     * @return returns pippo.RecuperoStatoOggettoRisposta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatoOggetto", targetNamespace = "http://ws.sacerasi.eng.it/", className = "pippo.GetStatoOggetto")
    @ResponseWrapper(localName = "getStatoOggettoResponse", targetNamespace = "http://ws.sacerasi.eng.it/", className = "pippo.GetStatoOggettoResponse")
    public RecuperoStatoOggettoRisposta getStatoOggetto(
            @WebParam(name = "nmAmbiente", targetNamespace = "") String nmAmbiente,
            @WebParam(name = "nmVersatore", targetNamespace = "") String nmVersatore,
            @WebParam(name = "cdKeyObject", targetNamespace = "") String cdKeyObject);
}
